[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "EditorAttributes"
authors = [{name = "v0lt", email = "v0lt130852@gmail.com"}]
dynamic = ["version", "description"]
